apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pdftools-iyazerski-dev
  labels:
    app: pdf-tools
spec:
  secretName: pdftools-iyazerski-dev-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - pdftools.iyazerski.dev
