apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pdf-tools
  labels:
    app: pdf-tools
spec:
  rules:
    - host: pdf-tools.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pdf-tools
                port:
                  name: http

