apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pdf-tools
  labels:
    app: pdf-tools
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/hsts: "true"
    nginx.ingress.kubernetes.io/hsts-max-age: "31536000"
    nginx.ingress.kubernetes.io/hsts-preload: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - pdftools.iyazerski.dev
      secretName: pdftools-iyazerski-dev-tls
  rules:
    - host: pdftools.iyazerski.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pdf-tools
                port:
                  name: http
