apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  labels:
    app: pdf-tools
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  labels:
    app: pdf-tools
spec:
  headers:
    contentTypeNosniff: true
    frameDeny: true
    browserXssFilter: true
    stsSeconds: 31536000
    stsIncludeSubdomains: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: buffering
  labels:
    app: pdf-tools
spec:
  buffering:
    maxRequestBodyBytes: 319815680
    memRequestBodyBytes: 10485760
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: pdf-tools-transport
  labels:
    app: pdf-tools
spec:
  forwardingTimeouts:
    dialTimeout: 30s
    responseHeaderTimeout: 600s
    idleConnTimeout: 600s
